openapi: 3.0.0

servers:
  - description: OBADA Staging API
    url: https://dev.api.obada.io
  - description: OBADA Production API
    url: http://api.obada.io

info:
  version: "0.0.1"
  title: OBADA API
  termsOfService: 'https://www.obada.io/terms/'
  contact:
    name: Obada Dev Team
    email: techops@obada.io
    url: 'https://www.obada.io'

tags:
  - name: Obit

paths:
  /obit/checksum:
    post:
      summary: Generates the obit checksum.
      description: ''
      operationId: checksum
      tags:
        - Obit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obit'
      responses:
        "200":
          $ref: '#/components/responses/ChecksumResponse'
        "422":
          $ref: "#components/responses/UnprocessableEntity"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /obit/id:
    post:
      summary: Generate Obit ID
      description: 'Returns the Obit ID for a given device_id, part_number and serial_number input.'
      operationId: generateId
      tags:
        - Obit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestObitId'
      responses:
        "200":
          $ref: "#/components/responses/ObitIdResponse"
        "422":
          $ref: "#components/responses/UnprocessableEntity"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /obits:
    get:
      tags:
        - Obit
      description: Implements a fulltext search for obits by "searchTerm".
      operationId: search
      parameters:
        - name: q
          description: Query argument that used for a fulltext search
          in: query
          schema:
            type: string
            example: "fe403a1afe16203f4b8bb3a0e72d3e17567897bc15293e4a87b663e441030aea"
        - name: offset
          in: query
          description: Number of records to skip for pagination.
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        "200":
          description: List of obits responded by given arguments.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Obits"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - Obit
      description: Creates a new obit.
      operationId: createObit
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Obit"
      responses:
        "201":
          $ref: "#/components/responses/ObitCreated"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /obits/{obit_did}:
    parameters:
      - name: obit_did
        in: path
        description: The given ObitDID argument
        required: true
        schema:
          type: string
          example: "did:obada:fe096095-e0f0-4918-9607-6567bd5756b5"

    get:
      tags:
        - Obit
      description: Shows the information about single Obit by given ObitDID
      operationId: showObit
      responses:
        "200":
          description: Obit in response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Obit"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

    put:
      tags:
        - Obit
      description: Updates Obit by given ObitDID with payload
      operationId: updateObit
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Obit"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      tags:
        - Obit
      description: Changes Obit status to DISABLED_BY_OWNER
      operationId: removeObit
      responses:
        "200":
          $ref: "#/components/responses/NoContent"
        "404":
          $ref: "#/components/responses/NotFound"

  /obits/{obit_did}/history:
    get:
      tags:
        - Obit
      description: Shows the history of changes by given Obit with ObitDID
      operationId: showObitHistory
      parameters:
        - name: obit_did
          in: path
          description: The given ObitDID argument
          required: true
          schema:
            type: string
            example: "did:obada:fe096095-e0f0-4918-9607-6567bd5756b5"
      responses:
        "200":
          $ref: "#/components/responses/ObitHistoryResponse"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    RequestObitId:
      $ref: "definitions/Obit.yml#/RequestObitId"
    Obits:
      $ref: "definitions/Obit.yml#/Obits"
    Obit:
      $ref: "definitions/Obit.yml#/Obit"
    ObitHistory:
      $ref: "definitions/Obit.yml#/ObitHistory"
  responses:
    ObitIdResponse:
      description: Obit ID response
      content:
        application/json:
          schema:
            $ref: "definitions/Obit.yml#/ObitId"

    ChecksumResponse:
      description: Obit checksum response
      content:
        application/json:
          schema:
            $ref: "definitions/Obit.yml#/Checksum"

    ObitHistoryResponse:
      description: Collection of historical changes for given obit
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/ObitHistory"
    ObitCreated:
      description: Collection of historical changes for given obit
      content:
        application/json:
          schema:
            type: object
            properties:
              did:
                type: string
              usn:
                type: string
              hash:
                type: string
    Created:
      description: The request was successful and the resource was created.
    NoContent:
      description: The request was successful and no content was returned.
    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: "Errors.yml#/InternalServerError"
    BadRequest:
      description: The request was malformed.
    NotFound:
      description: The requested resource could not be found.
      content:
        application/json:
          schema:
            $ref: "Errors.yml#/NotFound"
    UnprocessableEntity:
      description: The submitted entity could not be processed.
      content:
        application/json:
          schema:
            $ref: "Errors.yml#/UnprocessableEntity"
