---
- name: Install unattended upgrades package.
  apt: name=unattended-upgrades state=present
  become: yes

- name: setup unattended-upgrades configuration file
  notify: unattended-upgrades restart
  template:
    src: ./templates/etc/unattended-upgrades/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  become: yes

- name: setup unattended-upgrades schedule
  notify: unattended-upgrades restart
  template:
    src: ./templates/etc/unattended-upgrades/10periodic
    dest: /etc/apt/apt.conf.d/10periodic
  become: yes

- name: ensure unattended-upgrades service is started and enabled
  service: name=unattended-upgrades enabled=true state=started
  become: yes