---
- hosts: all

  tasks:
    - name: "Copy docker-compose.yml"
      template:
        src: docker-compose.yml.j2
        dest: "{{ deployment_path }}/docker-compose.yml"
        mode: 0644

    - name: "Run `docker-compose up`"
      docker_compose:
        project_src: "{{ deployment_path }}"
        build: no
        files:
          - docker-compose.yml
        recreate: smart