name: OBADA Node CI

on:
  push:
    branches:
    tags:
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: install golangci-lint and goveralls
        run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          mkdir -p ~/.ssh
          echo "${{ secrets.SDKGO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cd src
          export GOPRIVATE=github.com/obada-foundation
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.39.0
          go get -u github.com/mattn/goveralls
          go mod tidy
          go mod vendor

      - name: test and lint
        run: |
          cd src
          go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          $GITHUB_WORKSPACE/golangci-lint --config ${GITHUB_WORKSPACE}/.golangci.yml run --print-issued-lines --out-format=github-actions ./...
        working-directory: .
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "America/New_York"

      - name: submit coverage
        run: |
          cd src
          $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        working-directory: .
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}