name: Open API deployment

on: [push, pull_request]

jobs:

  generate-api-clients:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: checkout-node-api-library
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.API_CLIENTS_SSH_KEY }}
          repository: obada-protocol/node-api-library
          path: node-api-library

      - id: lint
        run: make lint-openapi-spec

      - id: generate-node-api-library
        run: |
          git config --global user.name "OBADA TechOps Team"
          git config --global user.email "techops@obada.io"
          make deploy-node-api-library
