name: Open API deployment

on: [push, pull_request]

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
    - id: lint
      run: echo "Perform some linting there"

  deploy-api-spec:
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "Deploy api spec"

  generate-api-clients:
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: checkout-php-client
        uses: actions/checkout@v2
        run: |
          git checkout git@github.com:obada-protocol/php-client-library

      - id: check
        run: ls -la

      - id: generate-php-client
        run: make deploy-php-client