name: Open API deployment

on: [push, pull_request]

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
    - id: lint
      run: echo "Perform some linting there"

  deploy-api-spec:
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "Deploy api spec"

  generate-api-clients:
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: checkout-php-client
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.API_CLIENTS_SSH_KEY }}
          repository: obada-protocol/php-client-library
          path: php-api-client

      - id: generate-php-client
        run: |
          git config user.name OBADA TechOps Team
          git config user.email techops@obada.io
          make deploy-php-client